#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""mini_dump.py - a deliberately tiny, hand-written USDA reader for the tutorial.

This is NOT a generated target and NOT how the real parser is built. The real
single-layer parser is generated by an agent from the full skill subgraph (see
section 4, "The real workflow," in docs/tutorial/README.md). This ~50-line
stand-in exists only so you
can run the skill -> contract -> golden loop by hand once, and watch the harness
judge it.

It understands only the two shapes in docs/tutorial/hello.golden.json: an empty
layer, and a layer with root-level `def <Type> "<Name>" {}` prims. A real parser
owns far more (see skills/usda-spec-parser/SKILL.md); this one cuts every corner
that the tutorial cases let it cut.

Usage (the harness appends the input path as the final argument):

    py docs/tutorial/mini_dump.py <path-to.usda>      # Windows
    python3 docs/tutorial/mini_dump.py <path-to.usda> # Linux / macOS
"""

import json
import re
import sys

# Root-level `def <Type> "<Name>"` declarations. A real lexer/parser does this
# properly (skills/usda-lexical-format, skills/usda-spec-parser); we cheat with
# one regex because the tutorial cases only contain empty-bodied root prims.
PRIM_RE = re.compile(r'^\s*def\s+(\w+)\s+"([^"]+)"\s*$', re.MULTILINE)


def token_array(values):
    return {"type": "token[]", "value": values}


def main():
    text = open(sys.argv[-1], encoding="utf-8").read()
    prims = [(m.group(1), m.group(2)) for m in PRIM_RE.finditer(text)]
    names = [name for _type, name in prims]

    # The layer spec at "/" tracks its root prims in primChildren - the
    # usd-document-model contract's "child list maintenance" obligation.
    specs = {
        "/": {"kind": "layer", "fields": {"primChildren": token_array(names)}},
    }

    for type_name, name in prims:
        specs["/" + name] = {
            "kind": "prim",
            "fields": {
                "specifier": {"type": "specifier", "value": "def"},
                "typeName": {"type": "token", "value": type_name},
                # --- TUTORIAL TODO (Step 3) -------------------------------
                # score.py will fail "one-root-prim" here: the golden expects
                # every parsed prim spec to author its child-list fields, but
                # this stub omits them. Read skills/usd-document-model/SKILL.md
                # ("Child list maintenance" / "Required field authoring for
                # parsed specs"), then author the three empty child lists:
                #
                #     "primChildren": token_array([]),
                #     "propertyChildren": token_array([]),
                #     "variantSetChildren": token_array([]),
                #
                # Re-run score.py and watch the case flip to PASS.
                # ----------------------------------------------------------
            },
        }

    dump = {
        "ok": True,
        "diagnostics": [],
        "layer": {"fields": {"primChildren": token_array(names)}, "specs": specs},
    }
    print(json.dumps(dump))


if __name__ == "__main__":
    main()
